/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions'
import { Route as AppRemoteConfigRouteImport } from './routes/_app/remote-config'
import { Route as AppPromoRouteImport } from './routes/_app/promo'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppFeatureAccessRouteImport } from './routes/_app/feature-access'
import { Route as AppCreditsRouteImport } from './routes/_app/credits'
import { Route as AppAuditLogRouteImport } from './routes/_app/audit-log'
import { Route as AppAiUsageRouteImport } from './routes/_app/ai-usage'
import { Route as AppAiOpsRouteImport } from './routes/_app/ai-ops'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin-users'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users.index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users.$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppRemoteConfigRoute = AppRemoteConfigRouteImport.update({
  id: '/remote-config',
  path: '/remote-config',
  getParentRoute: () => AppRoute,
} as any)
const AppPromoRoute = AppPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppFeatureAccessRoute = AppFeatureAccessRouteImport.update({
  id: '/feature-access',
  path: '/feature-access',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAiUsageRoute = AppAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AppRoute,
} as any)
const AppAiOpsRoute = AppAiOpsRouteImport.update({
  id: '/ai-ops',
  path: '/ai-ops',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admin-users': typeof AppAdminUsersRoute
  '/ai-ops': typeof AppAiOpsRoute
  '/ai-usage': typeof AppAiUsageRoute
  '/audit-log': typeof AppAuditLogRoute
  '/credits': typeof AppCreditsRoute
  '/feature-access': typeof AppFeatureAccessRoute
  '/notifications': typeof AppNotificationsRoute
  '/promo': typeof AppPromoRoute
  '/remote-config': typeof AppRemoteConfigRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin-users': typeof AppAdminUsersRoute
  '/ai-ops': typeof AppAiOpsRoute
  '/ai-usage': typeof AppAiUsageRoute
  '/audit-log': typeof AppAuditLogRoute
  '/credits': typeof AppCreditsRoute
  '/feature-access': typeof AppFeatureAccessRoute
  '/notifications': typeof AppNotificationsRoute
  '/promo': typeof AppPromoRoute
  '/remote-config': typeof AppRemoteConfigRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/': typeof AppIndexRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin-users': typeof AppAdminUsersRoute
  '/_app/ai-ops': typeof AppAiOpsRoute
  '/_app/ai-usage': typeof AppAiUsageRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/credits': typeof AppCreditsRoute
  '/_app/feature-access': typeof AppFeatureAccessRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/promo': typeof AppPromoRoute
  '/_app/remote-config': typeof AppRemoteConfigRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-users'
    | '/ai-ops'
    | '/ai-usage'
    | '/audit-log'
    | '/credits'
    | '/feature-access'
    | '/notifications'
    | '/promo'
    | '/remote-config'
    | '/subscriptions'
    | '/users/$userId'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin-users'
    | '/ai-ops'
    | '/ai-usage'
    | '/audit-log'
    | '/credits'
    | '/feature-access'
    | '/notifications'
    | '/promo'
    | '/remote-config'
    | '/subscriptions'
    | '/'
    | '/users/$userId'
    | '/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admin-users'
    | '/_app/ai-ops'
    | '/_app/ai-usage'
    | '/_app/audit-log'
    | '/_app/credits'
    | '/_app/feature-access'
    | '/_app/notifications'
    | '/_app/promo'
    | '/_app/remote-config'
    | '/_app/subscriptions'
    | '/_app/'
    | '/_app/users/$userId'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/remote-config': {
      id: '/_app/remote-config'
      path: '/remote-config'
      fullPath: '/remote-config'
      preLoaderRoute: typeof AppRemoteConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promo': {
      id: '/_app/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof AppPromoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feature-access': {
      id: '/_app/feature-access'
      path: '/feature-access'
      fullPath: '/feature-access'
      preLoaderRoute: typeof AppFeatureAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-usage': {
      id: '/_app/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AppAiUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-ops': {
      id: '/_app/ai-ops'
      path: '/ai-ops'
      fullPath: '/ai-ops'
      preLoaderRoute: typeof AppAiOpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-users': {
      id: '/_app/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAiOpsRoute: typeof AppAiOpsRoute
  AppAiUsageRoute: typeof AppAiUsageRoute
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppFeatureAccessRoute: typeof AppFeatureAccessRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPromoRoute: typeof AppPromoRoute
  AppRemoteConfigRoute: typeof AppRemoteConfigRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAiOpsRoute: AppAiOpsRoute,
  AppAiUsageRoute: AppAiUsageRoute,
  AppAuditLogRoute: AppAuditLogRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppFeatureAccessRoute: AppFeatureAccessRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPromoRoute: AppPromoRoute,
  AppRemoteConfigRoute: AppRemoteConfigRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
